
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mysql-pv-volume
#  labels:
#    type: local
#spec:
#  storageClassName: standard
#  capacity:
#    storage: 250Mi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/data"
#---

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-pv-claim
#  labels:
#    app: mysql
#spec:
#  storageClassName: standard
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 250Mi
---      

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql   
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None

      
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_DATABASE
          value: db_example
        - name: MYSQL_ONETIME_PASSWORD
          value: "true"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
#         value: ThePassword
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password

#          value: Secret
        - name: MYSQL_USER
          value: springuser
        ports:
        - containerPort: 3306
          name: mysql
#        volumeMounts:
#        - name: mysql-persistent-storage
#          mountPath: /var/lib/mysql
#      volumes:
#      - name: mysql-persistent-storage
#        persistentVolumeClaim:
#          claimName: mysql-pv-claim
          
